---
title: "Project Notes"
description: |
  Documenting some pointers for the R code behind this project.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The following sources helped me solve specific challenges in my graphs!

You can also see this project's [Github repo here](https://github.com/katie-zhong/webtoon-originals-analysis).

* [R Naming Stylistic Guideline - Advanced R by Hadley Wickham](http://adv-r.had.co.nz/Style.html)
* [Horizontal Barplot in ggplot 2 - Stack Overflow](https://stackoverflow.com/questions/10941225/horizontal-barplot-in-ggplot2)
* [Rotating and spacing axis labels in ggplot 2 - Stack Overflow](https://stackoverflow.com/questions/1330989/rotating-and-spacing-axis-labels-in-ggplot2)
* [Remove grid and background from plot (ggplot2) - Felix Fan](https://felixfan.github.io/ggplot2-remove-grid-background-margin/)
* [How to change the color of bars of a bar plot using ggplot2 in R? - Tutorials Point](https://www.tutorialspoint.com/how-to-change-the-color-of-bars-of-a-bar-plot-using-ggplot2-in-r)
* [str_wrap function - RDocumentation](https://www.rdocumentation.org/packages/stringr/versions/1.4.0/topics/str_wrap)
* [Gradient colour scales (scale_colour_gradient)	- ggplot2 Documentation](https://ggplot2.tidyverse.org/reference/scale_gradient.html)
* [R Built-in Colors Cheat Sheet - Dr. Ying Wei](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf)
* [Trendline not appearing error - Stack Overflow](https://stackoverflow.com/questions/70107287/why-is-my-trendline-not-appearing-in-my-plot)
* [Adjustable table column sort filters - R Project](https://search.r-project.org/CRAN/refmans/DT/html/datatable.html)
* [R Pie Charts - Tutorials Point](https://www.tutorialspoint.com/r/r_pie_charts.htm#:~:text=A%20pie%2Dchart%20is%20a,numbers%20as%20a%20vector%20input.)
* [Merging data frames - RStudio](https://rstudio-pubs-static.s3.amazonaws.com/142359_100fcf07c1244d2c95dfab8901e1b8d3.html)
* [Add line to ggplot2 - GeeksforGeeks](https://www.geeksforgeeks.org/add-vertical-and-horizontal-lines-to-ggplot2-plot-in-r/)
* [Add text annotations to ggplot - Stack Overflow](https://stackoverflow.com/questions/28755576/add-text-to-ggplot)
* [Add variables in strings - Cookbook for R](http://www.cookbook-r.com/Strings/Creating_strings_from_variables/)