---
title: "Katie's WEBTOON Recommendations"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

It'd be criminal of me to create a WEBTOON-themed project and not provide recommendations, eh? Take a gander at some of my favorites below, in alphabetic order!

You can find the synopses online, so I'll just be providing my two cents. 😉


## Original Recommendations
* ***Big Jo*, Jungle Julia**
  + A lovely, light but also poignant read that explores body confidence and all the chaos of being a teenager exploring romantic connection and the world.
  + The series is finished and not on Daily Pass, which further cements its binge-worthy status!

* ***Eleceed*, Jeho Son and ZHENA**
  + A light read with humorous moments, mindboggling action scenes, and adorable  relationships (between friends, mentor-peers, and some hints of romantic ones). Electric (haha, that's an Eleceed reference) atmospheric art to pair!
  + (Also: the author draws cats in the absolute best way!)

* ***Heir's Game*, supsu**
  + 

* ***Moon You*, Cho Seok**
  + Absolutely hilarious read with fantastic art too. It is a Daily Pass series now, which means you can only read one episode per day for free. *Moon You* is a great read though, and Daily Pass does monetarily support the author!

* ***Muted*, Miranda Mundt**

* ***Parallel City*, Goda**
  + A very well done zombie apocalypse story with both intriguing plotlines revolving the apocalypse and its characters. Overall extremely high-quality.
  + But... maybe don't read this one at night. 😰

* ***Purple Hyacinth*, Ephemerys and Sophism**
  + Even if murder mystery with unbearable romantic tension isn't exactly your cup of tea, PH's undeniable quality may just win you over. The delightfully written characters and ingenious plot combined with the cinematic and deliberately meme-packed art make this one a veritable WEBTOON Original classic!

* ***Room of Swords*, Toonimated**
  + One of my favorite WEBTOONs of all time!
  + And that's despite being genuinely confusing to me haha; the plot is absolutely wild. Time travel, sci-fi, romance, psychological manipulation, colorful action scenes, the unexpected... Room of Swords has it all!

* ***See You in My 19th Life*, Lee Hey** 
 

* ***The Croaking*, echorise**
  + The first WEBTOON I read!

* ***The Red King*, Heylenne**

* ***Your Smile is a Trap*, AENGO**


## Canvas Recommendations
* ***BOMIC: A Bom Comic*, c2oh**

* ***BUUZA!*, Shazleen Khan**

* ***Carciphona*, Shilin**
  + One of my favorite authors/artists of all time; Shilin's art style and nuanced characters (morally-gray characters galore!) are incredibly beautiful and endearing.
  + I'll also recommend Shilin's *Amongst Us* (no, it's not related to the game Among Us), the modern spin-off of Carciphona!

* ***Immortal Affairs*, Blue.Owl**
  + A really interesting take on immortal beings, with characters that feel like real people and incredible character-driven storylines.
  + Some really great life lessons packed into the chapters too!

* ***Revelation of Eros*, AkumaYoru**
  + A very heartbreaking story, based on the true story of the author in the author-artist duo behind this WEBTOON.
  + There's comedy, friendship, and romance served alongside the characters' growth. Always hits me right in the feels.

* ***This Isekai Maid is Forming a Union!*, Frostlight Comics**
  + The nuanced looks at problematic media and multidimensional characters blow my mind each chapter!
  + The story is woven in a way that leads readers to decide for themselves what is wrong or right, and features satisfyingly competent characters, both in the protagonist and villain rosters.